bot = {'owner': '376384142599782410',
       'client_id': '720967691372068874',
       'version': '',
       'prefix': '+',
       'pstart': 'python3 ./main.py',
       'game': 'minecraft',
       'token': 'NzIwOTY3NjkxMzcyMDY4ODc0.Xw7VAg.wSHXcyUtrha9nknSB6v9keaVu4I',
       'invite_url': '',
       'update_name': '',
       'release_details': './data/misc/releaseplaceholder.txt',
       'checkin_details': './data/misc/checkin.txt',
       'checkin_channel': '',
       'update_details': './data/misc/update.txt',
       'startup_time': '',
       'pstart_time': '',
       'imgur_client_id': '',
       'imgur_client_secret': ''}
