bot = {'owner': '',
       'client_id': '',
       'version': '',
       'prefix': '|',
       'pstart': 'python3 ./main.py',
       'game': '',
       'token': '',
       'invite_url': '',
       'update_name': '',
       'release_details': './data/misc/releaseplaceholder.txt',
       'checkin_details': './data/misc/checkin.txt',
       'checkin_channel': '',
       'update_details': './data/misc/update.txt',
       'startup_time': '',
       'pstart_time': '',
       'imgur_client_id': '',
       'imgur_client_secret': ''}
